name: CI/CD Pipeline Final

on:
  push:
    branches: [ "main" ]

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      # 1. Instalar y Probar
      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Instalar dependencias
        run: npm install
        
      - name: Ejecutar prueba unitaria
        run: npm test

      # 2. Construir y Subir a Docker Hub
      - name: Login en Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Construir y subir imagen
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          # Usamos 'latest' para que Render siempre tome la última versión
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/practica-final-devops:latest

  # 3. Desplegar en Render
  deploy:
    needs: test-and-build
    runs-on: ubuntu-latest
    steps:
      - name: Disparar despliegue en Render
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}